# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Pipr::WS"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
    Thumbnail:
        cache: /tmp/pipr/thumb_cache
        compression: 7
        quality: 50

cache_dir: '/tmp/pipr/cache'

restrict_targets: 1

sites:
  test:
     sizes: [ '30x30', '100x30', '30x', 'x30', '300x', '600x' ]
     allowed_targets: [ 'public/images/test.png', 'non-existing-image', 'http://dghasdfguasdfhgiouasdhfguiohsdfg/non-existing-image' ]
     watermark: 
          string: cellbazaar.com
          font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
          a: cm
          color: [ 255, 255, 255 ]
  demo:
     sizes: [ '100x', '100x100', '200x', '300x', '144x82', '50x50', '76.8x43.2', '300x50', '169x169' ]
     allowed_targets: [ 'http://csp.picsearch.com' ]
     watermark: 
          string: cellbazaar.com
          font: /usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
          a: cm
          color: [ 255, 255, 255 ]
  hvordan:
     sizes: [ '100x', '100x100', '200x', '300x', '144x82', '50x50', '169x169' ]
     allowed_targets: [ 'http://hvordan.no', 'http://csp.picsearch.com' ]
  overblikk:
     sizes: [ '600x200', '300x300', '600x300', '200x600' ]
     allowed_targets: [ 'http' ]
