# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Pipr::WS"

port: 8080
#port: 4001

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "main"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding:  'utf8'
    start_tag: '[%'
    end_tag:   '%]'

plugins:
    Thumbnail:
        cache: /tmp/pipr/thumb_cache
        compression: 7
        quality: 50
    NullSQL::DB_File:
        basepath: /tmp/dancer
    NullSQL::Riak:
        host: http://dev-riak1.startsiden.dev:8098
        ua_timeout: 900

cache_dir: '/tmp/pipr/cache'

restrict_targets: 1

sites:
  test:
     sizes: [ '30x30', '100x30', '30x', 'x30' ]
     allowed_targets: [ 'public/images/test.png', 'non-existing-image', 'http://dghasdfguasdfhgiouasdhfguiohsdfg/non-existing-image' ]
  demo:
     sizes: [ '100x', '100x100', '200x', '300x', '144x82', '50x50', '76.8x43.2', '300x50', '169x169' ]
     allowed_targets: [ 'http://csp.picsearch.com' ]
  hvordan:
     sizes: [ '100x', '100x100', '200x', '300x', '144x82', '50x50', '169x169' ]
     allowed_targets: [ 'http://hvordan.no', 'http://csp.picsearch.com' ]
  overblikk:
     sizes: [ '600x200', '300x300', '600x300', '200x600', '150x400', '400x150', '300x200', '400x200', '200x400' ]
     allowed_targets: [ 'http' ]
