version: '2'
services:
    server:
        build:
            context: .
            dockerfile: Dockerfile
            args:
              DEBUG: 1
        image: pipr-ws
        container_name: run-pipr-ws
        dns:
            - 10.4.4.37
        volumes:
            - ./lib:/root/lib
            - ./bin:/root/bin
            - ./share:/root/share
            - ./t:/root/t
        ports:
            - "3000:3000"
