#!/bin/bash
echo "Killing all running Pipr containers."
docker ps | grep 'pipr-ws:latest' | awk '{print $1}' | xargs docker kill
echo "Removing all Pipr containers."
docker ps -a | grep 'pipr-ws:latest' | awk '{print $1}' | xargs docker rm
echo "Removing Pipr image."
docker rmi pipr-ws:latest
echo "Building New Pipr image."
docker build --no-cache -t pipr-ws .
echo "Running Pipr container."
docker run --name pipr-ws -v `pwd`:/pipr-ws -p 9000:3000 -d pipr-ws
